USE [master]
GO

/****** Object:  Database [Nachhilfe]    Script Date: 08.03.2023 11:37:42 ******/
CREATE DATABASE [Nachhilfe]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Nachhilfe', FILENAME = N'C:\SQL-Kurs\DB\Nachhilfe\Nachhilfe.mdf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 20%)
 LOG ON 
( NAME = N'Nachhilfe_log', FILENAME = N'C:\SQL-Kurs\DB\Nachhilfe\Nachhilfe_log.ldf' , SIZE = 10240KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Nachhilfe].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Nachhilfe] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Nachhilfe] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Nachhilfe] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Nachhilfe] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Nachhilfe] SET ARITHABORT OFF 
GO

ALTER DATABASE [Nachhilfe] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Nachhilfe] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Nachhilfe] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Nachhilfe] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Nachhilfe] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Nachhilfe] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Nachhilfe] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Nachhilfe] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Nachhilfe] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Nachhilfe] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Nachhilfe] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Nachhilfe] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Nachhilfe] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Nachhilfe] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Nachhilfe] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Nachhilfe] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Nachhilfe] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Nachhilfe] SET RECOVERY FULL 
GO

ALTER DATABASE [Nachhilfe] SET  MULTI_USER 
GO

ALTER DATABASE [Nachhilfe] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Nachhilfe] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Nachhilfe] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Nachhilfe] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Nachhilfe] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Nachhilfe] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Nachhilfe] SET  READ_WRITE 
GO


