USE [Nachhilfe]
GO

/****** Object:  Table [dbo].[tb_Unterrichtsart]    Script Date: 11.05.2023 20:48:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tb_Unterrichtsart](
	[ArtID] [int] IDENTITY(1,1) NOT NULL,
	[Bezeichnung] [nvarchar](20) NULL,
	[OrtOderMedium] [nvarchar](20) NULL,
 CONSTRAINT [PK_tb_Unterrichtsart] PRIMARY KEY CLUSTERED 
(
	[ArtID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_tb_UnterrichtsartBezeichnung] UNIQUE NONCLUSTERED 
(
	[Bezeichnung] ASC,
	[OrtOderMedium] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


